// SPDX-License-Identifier: MIT OR Apache-2.0

//! Ratchet handwritten automatic-routing thresholds until evidence generation owns them.

use std::{collections::BTreeSet, fs, path::Path};

use super::{repo_root, rust_sources};

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
enum ThresholdOwner {
    Handwritten,
    GeneratedEvidence,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct RouteThreshold {
    relative_path: String,
    name: String,
    owner: ThresholdOwner,
}

fn automatic_route_threshold_inventory() -> BTreeSet<RouteThreshold> {
    let root = repo_root();
    let mut thresholds = BTreeSet::new();
    for path in rust_sources(&root.join("crates")) {
        let relative = path
            .strip_prefix(root)
            .expect("route source must be inside the repository")
            .to_string_lossy()
            .replace('\\', "/");
        if !is_production_source(&relative, &path) {
            continue;
        }
        let source =
            fs::read_to_string(&path).unwrap_or_else(|error| panic!("read {relative}: {error}"));
        thresholds.extend(route_thresholds_in(&relative, &source));
    }
    thresholds
}

fn is_production_source(relative: &str, path: &Path) -> bool {
    relative.contains("/src/")
        && !relative.contains("/tests/")
        && !relative.contains("/test_support/")
        && !path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name == "tests.rs" || name.ends_with("_tests.rs"))
}

fn route_thresholds_in(relative_path: &str, source: &str) -> BTreeSet<RouteThreshold> {
    let owner = if relative_path.contains("/generated/") {
        ThresholdOwner::GeneratedEvidence
    } else {
        ThresholdOwner::Handwritten
    };
    source
        .lines()
        .map(str::trim_start)
        .filter(|line| !line.starts_with("//"))
        .filter_map(|line| line.split_once("const AUTO_").map(|(_, suffix)| suffix))
        .filter_map(|suffix| {
            let name = format!(
                "AUTO_{}",
                suffix
                    .split(|character: char| {
                        character == ':' || character == '=' || character.is_whitespace()
                    })
                    .next()?
            );
            name.contains("_MIN").then_some(RouteThreshold {
                relative_path: relative_path.into(),
                name,
                owner,
            })
        })
        .collect()
}

#[test]
fn automatic_route_thresholds_match_reviewed_migration_inventory() {
    let actual = automatic_route_threshold_inventory();
    let expected = BTreeSet::new();

    assert_eq!(
        actual, expected,
        "automatic-route threshold ownership changed; new handwritten values are forbidden, and \
         generated migrations must remove their handwritten inventory entries"
    );
}

#[test]
fn routing_domains_and_generated_promotion_ownership_are_explicit() {
    let root = repo_root();
    for adapter in ["j2k-cuda", "j2k-metal"] {
        let routing = root.join("crates").join(adapter).join("src/routing");
        for module in [
            "mod.rs",
            "eligibility.rs",
            "availability.rs",
            "promotion.rs",
            "decision.rs",
            "rejection.rs",
            "telemetry.rs",
        ] {
            assert!(
                routing.join(module).is_file(),
                "{adapter} routing must own {module}"
            );
        }
        let generated = root
            .join("crates")
            .join(adapter)
            .join("src/generated/promotion.rs");
        let source = fs::read_to_string(&generated)
            .unwrap_or_else(|error| panic!("read {}: {error}", generated.display()));
        assert!(source.contains("@generated by `cargo xtask promotion-codegen`"));
        assert!(source.contains("SOURCE_EVIDENCE"));
    }

    let manifest = root.join("docs/routing-promotion-evidence.json");
    let manifest_source = fs::read_to_string(&manifest)
        .unwrap_or_else(|error| panic!("read {}: {error}", manifest.display()));
    assert!(manifest_source.contains("\"schema_version\": 1"));
    assert!(manifest_source.contains("\"operation_coverage\""));

    let generator = fs::read_to_string(root.join("xtask/src/promotion_codegen.rs"))
        .expect("read promotion code generator");
    assert!(generator.contains("unsupported promotion evidence schema version"));
    assert!(generator.contains("required operation matrix"));
    assert!(generator.contains("generated promotion table is stale"));
    let xtask = fs::read_to_string(root.join("xtask/src/main.rs")).expect("read xtask root");
    assert!(xtask.contains("\"promotion-codegen\" =>"));

    for path in [
        root.join("crates/j2k-cuda/src/routing"),
        root.join("crates/j2k-metal/src/routing"),
    ] {
        for source_path in rust_sources(&path) {
            let source = fs::read_to_string(&source_path).expect("read routing source");
            assert!(!source.contains("artifact SHA"));
            assert!(!source.contains("artifact_sha256"));
        }
    }
}

#[test]
fn threshold_parser_distinguishes_generated_evidence_ownership() {
    let handwritten = route_thresholds_in(
        "crates/adapter/src/routing.rs",
        "pub(super) const AUTO_BATCH_MIN_COUNT: usize = 8;",
    );
    let generated = route_thresholds_in(
        "crates/adapter/src/generated/auto_routing.rs",
        "pub const AUTO_BATCH_MIN_COUNT: usize = 8;",
    );

    assert_eq!(
        handwritten,
        BTreeSet::from([threshold(
            "crates/adapter/src/routing.rs",
            "AUTO_BATCH_MIN_COUNT",
        )])
    );
    assert_eq!(
        generated,
        BTreeSet::from([RouteThreshold {
            relative_path: "crates/adapter/src/generated/auto_routing.rs".into(),
            name: "AUTO_BATCH_MIN_COUNT".into(),
            owner: ThresholdOwner::GeneratedEvidence,
        }])
    );
}

fn threshold(relative_path: &str, name: &str) -> RouteThreshold {
    RouteThreshold {
        relative_path: relative_path.into(),
        name: name.into(),
        owner: ThresholdOwner::Handwritten,
    }
}
